export const newsSlugs = [
  "mgenius-academy-shines-at-wecan-picnic",
  "mga-summer-camp-ai-humanoid-robot-camp",
  "mga-students-shine-at-math-kangaroo-2026",
  "when-mga-robots-arrived-at-one-of-the-worlds-most-loved-childrens-museums",
  "ep2-classroom-building-a-rainforest-one-layer-at-a-time",
  "ep1-classroom-building-a-first-earthquake-simulator",
  "ep3-classroom-from-a-can-of-soda-to-understanding-the-world-of-density",
  "ep4-classroom-designing-a-knob-controlled-lamp-and-discovering-how-electricity-works",
  "ep5-classroom-from-a-bluetooth-speaker-to-a-personal-blog-learning-like-real-engineers",
  "mga-workshop-classroom-from-bionic-hands-to-brainwave-headsets-young-scientists-are-creating-the-future",
  "student-engineering-portfolios-boston",
  "a-shadow-theater-light-science-event-at-wellesley-free-library",
  "stem-projects-for-kids-boston-ep2-smart-garden",
  "mga-open-house-on-may-9-discover-stem-innovation-and-entrepreneurship-for-grades-1-8",
  "mga-birthday-party-little-engineers-gravity-balance-car-challenge",
  "mga-invite-your-friend-week",
  "april-body-brain-electric-car-camp-recap",
  "2026-mga-springsummer-camp-new",
  "where-body-brain-meet-the-ocean-mga-summer-camp-field-trip-to-the-new-england-aquarium",
  "mga-summer-camp-scratch-coding-3d-design",
  "one-beam-of-light-one-story-one-cultural-connection-mga-shadow-studio",
  "mga-summer-camp-engineering-invention-camp",
  "2026-boston-makers-innovators-challenge",
  "mga-wins-4-of-6-special-awards-at-the-massachusetts-invention-convention-and-advances-to-u-s-nationals",
  "noetic-learning-math-contest-2026-spring-results",
  "noetic-learning-math-contest-award-celebration-2026",
  "noetic-learning-math-contest-2026-spring-award-celebration",
  "mga-students-shine-at-math-kangaroo-2026-16-national-state-honors",
] as const;

export type NewsSlug = (typeof newsSlugs)[number];
